server:
  port: 8082

# 配置文件加密key
jasypt:
  encryptor:
    password: root

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://118.123.16.211:3306/insurance_prod?characterEncoding=UTF-8&useSSL=true&allowMultiQueries=true
    username: root
    # Jasypt加密 可到common-utils中找到 JasyptUtil 加解密工具类生成加密结果 格式为ENC(加密结果)
    password: ENC(B6M4HhIardKWsVvF2xyTyR8lReyEBFeU)
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    logSlowSql: true

#=====================Swagger扫描路径
swagger_url: com.xxxcjkj.insurance.controller

#====================生产环境================
api_url: http://icm.52zzb.com/cm/channelService
channelUserId: qd_chemuzhi
channelSecret: zCjBITsovx3FO6NXt6j69fgjfGQXPCaH
privateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBAO6EbBtBromYnqUPvSq8a4+R+tH40eWC0446GrZs700TfGoF0xcQv+6TKuXMbUu0UmcH5ri/DYlite3toJ4JrrDd20FCSFTOWsABit5hCJRNmynGU7TpRHWjrLSXOaZd0R5nxiXTvjnR4BJz5Q8dJ3b1h+pjLbnAoItPZG+GaPOpAgMBAAECgYEAuVLI0LDLFXwxH91HxPHbvRTWxtjG9cYd7G93G/EuSjvuuk5GQrCwAIX2mdCpx12XfRhli3xe3zWEWBb/amvpf2EK4prSqzWzv3SXFIKPAY4BQyQ0SiA6kUb//D/t+t12smRTlLt5TvOpAH8FIhe87Yosxz9lXEnugy2yI3p2oGUCQQD6UgyseWJcgQTT5Y9c8LzaiSc4U+g8WMmE3j/V+gCsIMoTqGHh+aIuGGwUK/S/BYb1nfuCGlkNyqNqUCjLeFTTAkEA8+3Qv2N7NUfZtodqTndAPY9G3+iNGfirr2SeOzeUTVbSh/qg7u/zlLfRXjtWTMhtqK1FO+CgtLY3tW7YDJG4EwJAK01QRfHFkyz6cdFvSGuYr9E0CKlzLiVJzwNHVbOmtCAD9PyW2il95a1x3Ndxwi2pmAmZPXtjVmBsfnKZbAFH4wJBAL3HDF2a3ES7vdqQyFh71vMOAao6l2zZV1mCAsk3mJ4DKpC4oXTEItJVoQKbT601UnulMvQ+80kla3ow3s4IoRkCQGjQseOaJrrAPVdNUmPrtMUOfdnJeHH69/hxRTLv9FsVVAAz80Xy3Y1JTcTBefJtQFz/VmFS/fWkMSE6JxHTlpk=

